version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/mydatabase'
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && yarn run start:prod"

  db:
    image: postgres:15
    container_name: nestjs-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
